### ISSUE TITLE
Couldn't install the npm lib.

### ISSUE THREAD

**Issue by yogeshvar** [upwork/node-upwork-oauth2#1]
Trying out the new oauth2.0, I could not install the npm library node-upwork-oauth2

<img width="535" alt="screenshot 2019-01-17 at 12 02 57 pm" src="https://user-images.githubusercontent.com/17572818/51300714-e8fc4c80-1a52-11e9-92d6-ece1ac95a8ba.png">

Could you tell anyother I could get started with oauth2.0.! Thanks.!

**Comment by mnovozhylov** [comment]
Hello @yogeshvar 

thank you for your interest in the library. We're sorry for the inconvenience - the README file has been fixed.

Also, take into account, OAuth2 is in beta phase and is not available to everyone.
Still, if you like to continue, please use the following command `npm install @upwork/node-upwork-oauth2` or follow https://www.npmjs.com/package/@upwork/node-upwork-oauth2

**Comment by yogeshvar** [comment]
Thanks much @mnovozhylov 👍
