### ISSUE TITLE
Support for v3 api of Upwork.

### ISSUE THREAD

**Issue by yogeshvar** [upwork/node-upwork-oauth2#2]
As I working with the workDairy route, I have just found that 

`exports.Workdiary.prototype.get = function(company_id, date, params, callback){
  debug('running request');
  this.api.client.get('team/v3/workdiaries/companies/' + company_id + '/' + date, params, callback)
}`

Is not available in the WorkDiary route! 

Hoping for a stable release to utilize all the versions of the API. Thanks 😃

**Comment by mnovozhylov** [comment]
@yogeshvar , thank you for letting us know!
Fixed in `v2.0.3`.
