### ISSUE TITLE
Is there a way to search through job postings with new Upwork GraphQL API?

### ISSUE THREAD

**Issue by Mehoff** [upwork/node-upwork-oauth2#27]
Since Upwork is deprecating REST API support on December 15, I've started refactoring my application to support new GraphQL API. My main REST API requests are:

`Search Jobs: GET /api/profiles/v2/search/jobs.{format}`
`Get Job Profile: GET /api/profiles/v1/jobs/{job_key}.{format}`

The problem is, GraphQL API Docs does not seem to have similar requests in "Search" directory. Only thing I can search through, on a date of writing this question, are "freelancerProfileRecords". I can indeed get information about a specific job post using it's ID - it's written in API docs, but this does not cover my needs, and makes migration from REST API frustrating.

I need to have a filter mechanism using params such as: "title", "skills", "q" and so on, like it is written in REST docs [here](https://developers.upwork.com/?lang=python#jobs_search-for-jobs).

Is there a workaround, or did I just miss something?

**Comment by mnovozhylov** [comment]
I'm sorry that you experience difficulties during the migration. Please, contact [Support Team](https://support.upwork.com/hc/en-us/categories/115002435568) if you need further assistance.

I close the issue, because it's unrelated to the library functionality.
