### ISSUE TITLE
When does this project planned to be production-ready?

### ISSUE THREAD

**Issue by maozedong** [upwork/node-upwork-oauth2#3]
Hey, glad to see new api version!
Any plans of when will it be production-ready?
What are the main differences compared to [v1 library](https://github.com/upwork/node-upwork)?
Is `promise` interface planned?
Also typescript typings may be helpful, since upwork responds with a lot of different entities
Thanks!

**Comment by mnovozhylov** [comment]
Hello @maozedong ,

this version of the library was developed to support OAuth2 authentication which is in Beta phase. Please, read more here - [https://developers.upwork.com/#authentication-beta_oauth-20](https://developers.upwork.com/#authentication-beta_oauth-20)
